import re
import sys

def apply_refinements(file_path):
    print(f"Applying refinements to {file_path}")
    with open(file_path, 'r') as f:
        content = f.read()
    
    # 1. Fix Duplicate Headings (Introduction followed by Introduction)
    # Pattern: \section{Introduction} ... \section{Introduction}
    if content.count(r'\section{Introduction}') > 1:
        print(" - Removing duplicate 'Introduction' section header")
        # Replace the second occurrence? Or the first? 
        # Usually the template adds one, and the content adds one.
        # Let's keep the one that looks Structural (usually the first).
        # We'll replace subsequent matches with empty string.
        parts = content.split(r'\section{Introduction}')
        # Reconstruct: Part 0 + Header + Part 1 + (no header) + Part 2...
        new_content = parts[0] + r'\section{Introduction}' + "".join(parts[1:])
        content = new_content
        
    # 2. Fix Margin Notes (Remove Text Names)
    # The requirement: Margin notes should NOT have text names, just the image.
    # Pattern: \automarginnote{\includegraphics[...]{...} Name}
    # We want: \automarginnote{\includegraphics[...]{...}}
    
    # Regex to find automarginnote containing includegraphics AND extra text
    # \automarginnote { \includegraphics [.*?] {.*?} .*? }
    # We need to capture the graphics part and discarding the text part.
    
    def replacer(match):
        full_note = match.group(0)
        graphics_part = match.group(1) # The \includegraphics{...} command
        
        # Check if there is text after graphics
        # If the group(0) ends with just '}', it's fine.
        # But regex is tricky with nested braces.
        
        # Simpler approach: Rebuild the note
        # Assuming format: \automarginnote{ \includegraphics...{...} ... }
        return f"\\automarginnote{{{graphics_part}}}"

    # Pattern captures \includegraphics...{...} inside \automarginnote{ ... }
    # This regex assumes standard LaTeX formatting generated by our tools
    # It matches \automarginnote{ (capture logic) (text) }
    pattern = r'\\automarginnote\s*\{\s*(\\includegraphics\[.*?\]\{.*?\})\s*(.*?)\s*\}'
    
    matches = re.findall(pattern, content)
    if matches:
        print(f" - Fixing {len(matches)} margin notes (removing text names)")
        content = re.sub(pattern, r'\\automarginnote{\1}', content)
        
    # 2b. Secondary cleanup for \it \small Name
    pattern2 = r'\\automarginnote\s*\{\s*(\\includegraphics\[.*?\]\{.*?\})\s*\\it\s*\\small\s*(.*?)\s*\}'
    content = re.sub(pattern2, r'\\automarginnote{\1}', content)

    with open(file_path, 'w') as f:
        f.write(content)
    print("Refinements complete.")

if __name__ == "__main__":
    apply_refinements("/Users/davidlary/Dropbox/Apps/Overleaf/MachineLearningBook/Chapter-Introduction.tex")
